PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?subject1 ?predicate1 ?object1 ?subject2 ?predicate2 ?object2
WHERE {
  {
    ?edge1 a rdf:Statement ;
           rdf:subject __START__ ;
           rdf:predicate ?predicate1 ;
           rdf:object ?node1 .
    ?edge2 a rdf:Statement ;
           rdf:subject ?node1 ;
           rdf:predicate ?predicate2 ;
           rdf:object __END__ .
    BIND(__START__ AS ?subject1)
    BIND(?node1 AS ?object1)
    BIND(?node1 AS ?subject2)
    BIND(__END__ AS ?object2)
  }
  UNION
  {
    ?edge1 a rdf:Statement ;
           rdf:subject __START__ ;
           rdf:predicate ?predicate1 ;
           rdf:object ?node1 .
    ?edge2 a rdf:Statement ;
           rdf:subject __END__ ;
           rdf:predicate ?predicate2 ;
           rdf:object ?node1 .
    BIND(__START__ AS ?subject1)
    BIND(?node1 AS ?object1)
    BIND(__END__ AS ?subject2)
    BIND(?node1 AS ?object2)
  }
  UNION
  {
    ?edge1 a rdf:Statement ;
           rdf:subject ?node1 ;
           rdf:predicate ?predicate1 ;
           rdf:object __START__ .
    ?edge2 a rdf:Statement ;
           rdf:subject ?node1 ;
           rdf:predicate ?predicate2 ;
           rdf:object __END__ .
    BIND(?node1 AS ?subject1)
    BIND(__START__ AS ?object1)
    BIND(?node1 AS ?subject2)
    BIND(__END__ AS ?object2)
  }
  UNION
  {
    ?edge1 a rdf:Statement ;
           rdf:subject ?node1 ;
           rdf:predicate ?predicate1 ;
           rdf:object __START__ .
    ?edge2 a rdf:Statement ;
           rdf:subject __END__ ;
           rdf:predicate ?predicate2 ;
           rdf:object ?node1 .
    BIND(?node1 AS ?subject1)
    BIND(__START__ AS ?object1)
    BIND(__END__ AS ?subject2)
    BIND(?node1 AS ?object2)
  }
}
__LIMIT__
__OFFSET__
